### ISSUE TITLE
fta.samples.models.Sample.labeledsample.RelatedObjectDoesNotExist after adding new frozen page

### ISSUE THREAD

**Issue by reuben** [mozilla-applied-ml/fta#29]
When starting the project from a fresh DB and then adding a sample, the sample list page fails with:

```
ERROR 2020-11-01 05:50:31,481 log 24194 123145513644032 Internal Server Error: /samples
Traceback (most recent call last):
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django/test/utils.py", line 95, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django/test/utils.py", line 95, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django_tables2/templatetags/django_tables2.py", line 167, in render
    return template.render(context={"table": table}, request=request)
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django/test/utils.py", line 95, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django/template/loader_tags.py", line 53, in render
    result = self.nodelist.render(context)
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django/template/loader_tags.py", line 53, in render
    result = self.nodelist.render(context)
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django/template/loader_tags.py", line 53, in render
    result = self.nodelist.render(context)
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django/template/loader_tags.py", line 53, in render
    result = self.nodelist.render(context)
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django/template/defaulttags.py", line 165, in render
    values = list(values)
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django_tables2/rows.py", line 244, in items
    column.current_value = self.get_cell(column.name)
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django_tables2/rows.py", line 197, in get_cell
    return self._get_and_render_with(
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django_tables2/rows.py", line 173, in _get_and_render_with
    return render_func(bound_column, value)
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django_tables2/rows.py", line 206, in _call_render
    content = call_with_appropriate(bound_column.render, render_kwargs)
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django_tables2/utils.py", line 572, in call_with_appropriate
    return fn(**kwargs)
  File "/Users/reubenmorais/Development/fta/fta/samples/tables.py", line 39, in render_labels
    labeled_elements = record.labeledsample.labeledelement_set.all()
  File "/Users/reubenmorais/.local/share/virtualenvs/fta-j0WEaS1O/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 420, in __get__
    raise self.RelatedObjectDoesNotExist(
fta.samples.models.Sample.labeledsample.RelatedObjectDoesNotExist: Sample has no labeledsample.
```

**Comment by birdsarah** [comment]
doh! will fix!
